// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP3zORyH5QZFJgNxX5NY9GinONseweoJc',
    appId: '1:338587847382:web:123456789',
    messagingSenderId: '338587847382',
    projectId: 'stira-d2043',
    authDomain: 'stira-d2043.firebaseapp.com',
    storageBucket: 'stira-d2043.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP3zORyH5QZFJgNxX5NY9GinONseweoJc',
    appId: '1:338587847382:android:e6a625df2f7964d3239777',
    messagingSenderId: '338587847382',
    projectId: 'stira-d2043',
    storageBucket: 'stira-d2043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP3zORyH5QZFJgNxX5NY9GinONseweoJc',
    appId: '1:338587847382:ios:123456789',
    messagingSenderId: '338587847382',
    projectId: 'stira-d2043',
    storageBucket: 'stira-d2043.firebasestorage.app',
    iosBundleId: 'com.stira.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP3zORyH5QZFJgNxX5NY9GinONseweoJc',
    appId: '1:338587847382:ios:123456789',
    messagingSenderId: '338587847382',
    projectId: 'stira-d2043',
    storageBucket: 'stira-d2043.firebasestorage.app',
    iosBundleId: 'com.stira.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP3zORyH5QZFJgNxX5NY9GinONseweoJc',
    appId: '1:338587847382:web:123456789',
    messagingSenderId: '338587847382',
    projectId: 'stira-d2043',
    authDomain: 'stira-d2043.firebaseapp.com',
    storageBucket: 'stira-d2043.firebasestorage.app',
  );
}
